// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyhgastpybvprlwyoigc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5aGdhc3RweWJ2cHJsd3lvaWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzQ5OTEsImV4cCI6MjA3MzYxMDk5MX0.I3eJmw2XD708TQUAolmu9vYshvjek9A-YO-FDMekops";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});